### ISSUE TITLE
Add CI to check data generated by codegen is latest

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_smooth#134]
for example, python refresh_all.py; git diff

**Comment by fzyzcjy** [comment]
```
gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
  env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/flutter_smooth/flutter_smooth/scripts/generation/__main__.py", line 23, in <module>
    main(ci=args.ci)
  File "/home/runner/work/flutter_smooth/flutter_smooth/scripts/generation/__main__.py", line 11, in main
    fetch_github_pr.main()
  File "/home/runner/work/flutter_smooth/flutter_smooth/scripts/generation/fetch_github_pr.py", line 29, in main
    items += fetch_repo('flutter', 'flutter')
  File "/home/runner/work/flutter_smooth/flutter_smooth/scripts/generation/fetch_github_pr.py", line [17](https://github.com/fzyzcjy/flutter_smooth/actions/runs/3263010970/jobs/5361009002#step:4:18), in fetch_repo
    assert result.returncode == 0
AssertionError
main start (ci=True)

**Comment by fzyzcjy** [comment]
```
diff --git a/website/docs/insight/_conversation_generated.mdx b/website/docs/insight/_conversation_generated.mdx
index f70d01c..fda0909 100644
--- a/website/docs/insight/_conversation_generated.mdx
+++ b/website/docs/insight/_conversation_generated.mdx
@@ -32[5](https://github.com/fzyzcjy/flutter_smooth/actions/runs/3263028207/jobs/5361066189#step:5:6)[6](https://github.com/fzyzcjy/flutter_smooth/actions/runs/3263028207/jobs/5361066189#step:5:7),15 +3256,15 @@ Consider this proposal as such kind of "tween creator", then maybe dev will feel
 
 </DiscussionComment>
 
-<DiscussionComment author="dnfield" link="https://discord.com/channels/60801460331[7](https://github.com/fzyzcjy/flutter_smooth/actions/runs/3263028207/jobs/5361066189#step:5:8)93614[8](https://github.com/fzyzcjy/flutter_smooth/actions/runs/3263028207/jobs/5361066189#step:5:9)/608021234516754444/1021[9](https://github.com/fzyzcjy/flutter_smooth/actions/runs/3263028207/jobs/5361066189#step:5:10)93719337058359" source="discord" createTime="2022-09-21T03:58:[10](https://github.com/fzyzcjy/flutter_smooth/actions/runs/3263028207/jobs/5361066189#step:5:11).415+00:00" retrieveTime="2022-10-17T[11](https://github.com/fzyzcjy/flutter_smooth/actions/runs/3263028207/jobs/5361066189#step:5:12):35:13.053450">
+<DiscussionComment author="dnfield" link="https://discord.com/channels/608014603317936148/1021987751710699632/1021993719337058354" source="discord" createTime="2022-09-21T03:58:10.415+00:00" retrieveTime="2022-10-17T11:35:25.618280">
 
-Started a thread.
 
-</DiscussionComment>
 
-<DiscussionComment author="dnfield" link="https://discord.com/channels/608014603317936148/1021987751710699632/1021993719337058354" source="discord" createTime="2022-09-21T03:58:10.415+00:00" retrieveTime="2022-10-17T11:35:25.618280">
+</DiscussionComment>
 
+<DiscussionComment author="dnfield" link="https://discord.com/channels/608014603317936148/60802[12](https://github.com/fzyzcjy/flutter_smooth/actions/runs/3263028207/jobs/5361066189#step:5:13)34516754444/1021993719337058359" source="discord" createTime="2022-09-21T03:58:10.415+00:00" retrieveTime="2022-10-17T11:35:[13](https://github.com/fzyzcjy/flutter_smooth/actions/runs/3263028207/jobs/5361066189#step:5:14).053450">
 
+Started a thread.
 
 </DiscussionComment>

**Comment by fzyzcjy** [comment]
![image](https://user-images.githubusercontent.com/5236035/196110597-fa27c510-d2b6-47f8-82d2-ee07d9d89a3c.png)
