### ISSUE TITLE
Unit test `SmoothPreemptPoint`

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_smooth#16]

**Comment by fzyzcjy** [comment]
```
/Volumes/MyExternal/ExternalRefCode/flutter/bin/flutter --no-color test --machine --start-paused test/src/preempt_point_test.dart
Testing started at 19:43 ...
/Volumes/MyExternal/ExternalRefCode/flutter/packages/flutter/lib/src/scheduler/binding.dart:990:11: Error: 'LastVsyncInfo' isn't a type.
    final LastVsyncInfo raw = platformDispatcher.lastVsyncInfo();
          ^^^^^^^^^^^^^
/Volumes/MyExternal/ExternalRefCode/flutter/packages/flutter/lib/src/scheduler/binding.dart:990:50: Error: The method 'lastVsyncInfo' isn't defined for the class 'PlatformDispatcher'.
 - 'PlatformDispatcher' is from 'dart:ui'.
Try correcting the name to the name of an existing method, or defining a method named 'lastVsyncInfo'.
    final LastVsyncInfo raw = platformDispatcher.lastVsyncInfo();
                                                 ^^^^^^^^^^^^^

Failed to load "/Users/tom/RefCode/flutter_smooth/packages/smooth/test/src/preempt_point_test.dart": Compilation failed for testPath=/Users/tom/RefCode/flutter_smooth/packages/smooth/test/src/preempt_point_test.dart

**Comment by fzyzcjy** [comment]
(base) ➜  flutter git:(experiment-smooth) ./tools/gn --unoptimized
(base) ➜  flutter git:(experiment-smooth) ninja -C /Volumes/MyExternal/ExternalRefCode/engine/src/out/host_debug_unopt

**Comment by fzyzcjy** [comment]
```
(base) ➜  flutter git:(experiment-smooth) ninja -C /Volumes/MyExternal/ExternalRefCode/engine/src/out/host_debug_unopt 
ninja: Entering directory `/Volumes/MyExternal/ExternalRefCode/engine/src/out/host_debug_unopt'
[0/1] Regenerating ninja files
[123/294] LINK ./fml_unittests
FAILED: fml_unittests 
../../buildtools/mac-x64/clang/bin/clang++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.13.0 -arch x86_64 -nostdlib++ -stdlib=libc++ -Wl,-search_paths_first -L. -Wl,-rpath,@loader_path/. -Wl,-rpath,@loader_path/../../.. -Wl,-pie  -Xlinker -rpath -Xlinker @executable_path/Frameworks -o ./fml_unittests -Wl,-filelist,./fml_unittests.rsp  -ldl -lpthread -framework Foundation -framework ApplicationServices -framework OpenGL -framework AppKit -framework Metal -framework CoreFoundation -framework Security -framework CoreServices
ld64.lld: error: undefined symbol: flutter::LastVsyncInfo::ReadToDart()
>>> referenced by dart_args.h:315 (../../flutter/third_party/tonic/dart_args.h:315)
>>>               obj/flutter/lib/ui/ui.dart_ui.o:(symbol tonic::FfiDispatcher<void, _Dart_Handle* (*)(), &flutter::LastVsyncInfo::ReadToDart()>::Call()+0x17)
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
[124/294] LINK ./jni_unittests
FAILED: jni_unittests 
../../buildtools/mac-x64/clang/bin/clang++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.13.0 -arch x86_64 -nostdlib++ -stdlib=libc++ -Wl,-search_paths_first -L. -Wl,-rpath,@loader_path/. -Wl,-rpath,@loader_path/../../.. -Wl,-pie  -Xlinker -rpath -Xlinker @executable_path/Frameworks -o ./jni_unittests -Wl,-filelist,./jni_unittests.rsp  -ldl -lpthread -framework Foundation -framework ApplicationServices -framework OpenGL -framework AppKit -framework Metal -framework CoreFoundation -framework Security -framework CoreServices
ld64.lld: error: undefined symbol: flutter::LastVsyncInfo::ReadToDart()
>>> referenced by dart_args.h:315 (../../flutter/third_party/tonic/dart_args.h:315)
>>>               obj/flutter/lib/ui/ui.dart_ui.o:(symbol tonic::FfiDispatcher<void, _Dart_Handle* (*)(), &flutter::LastVsyncInfo::ReadToDart()>::Call()+0x17)
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
[129/294] LINK ./runtime_unittests
FAILED: runtime_unittests 
../../buildtools/mac-x64/clang/bin/clang++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.13.0 -arch x86_64 -nostdlib++ -stdlib=libc++ -Wl,-search_paths_first -L. -Wl,-rpath,@loader_path/. -Wl,-rpath,@loader_path/../../.. -Wl,-pie -Xlinker -exported_symbols_list -Xlinker ../../flutter/common/exported_symbols_mac.sym  -Xlinker -rpath -Xlinker @executable_path/Frameworks -o ./runtime_unittests -Wl,-filelist,./runtime_unittests.rsp  -ldl -lpthread -framework Foundation -framework ApplicationServices -framework OpenGL -framework AppKit -framework Metal -framework CoreFoundation -framework Security -framework CoreServices
ld64.lld: error: undefined symbol: flutter::LastVsyncInfo::ReadToDart()
>>> referenced by dart_args.h:315 (../../flutter/third_party/tonic/dart_args.h:315)
>>>               obj/flutter/lib/ui/ui.dart_ui.o:(symbol tonic::FfiDispatcher<void, _Dart_Handle* (*)(), &flutter::LastVsyncInfo::ReadToDart()>::Call()+0x17)
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
[136/294] CXX obj/flutter/shell/common/shell_unittests.shell_unittests.o
ninja: build stopped: subcommand failed.

**Comment by fzyzcjy** [comment]
try to modify a few char in vsync_waiter.h and rerun ninja

**Comment by fzyzcjy** [comment]
notice the tests fail. maybe really need to add to compile?

**Comment by fzyzcjy** [comment]
anyway no need to compile?

**Comment by fzyzcjy** [comment]
Know it: `/Volumes/MyExternal/ExternalRefCode/flutter/bin/flutter --no-color test --machine --start-paused test/src/preempt_point_test.dart` is wrong! need to specify local engine?

**Comment by fzyzcjy** [comment]
```
(base) ➜  smooth git:(master) /Volumes/MyExternal/ExternalRefCode/flutter/bin/flutter --local-engine-src-path=/Volumes/MyExternal/ExternalRefCode/engine/src --local-engine=android_debug_unopt_x64 test
00:07 +0 -1: loading /Users/tom/RefCode/flutter_smooth/packages/smooth/test/src/preempt_point_test.dart [E]                                                                      
  Failed to load "/Users/tom/RefCode/flutter_smooth/packages/smooth/test/src/preempt_point_test.dart":
  Failed to find "/Volumes/MyExternal/ExternalRefCode/engine/src/out/android_debug_unopt_x64/flutter_tester" in the search path.
    Command: /Volumes/MyExternal/ExternalRefCode/engine/src/out/android_debug_unopt_x64/flutter_tester 

To run this test again: /Volumes/MyExternal/ExternalRefCode/flutter/bin/cache/dart-sdk/bin/dart test /Users/tom/RefCode/flutter_smooth/packages/smooth/test/src/preempt_point_test.dart -p vm --plain-name 'loading /Users/tom/RefCode/flutter_smooth/packages/smooth/test/src/preempt_point_test.dart'
00:07 +0 -1: Some tests failed.

**Comment by fzyzcjy** [comment]
## this command works

```
(base) ➜  smooth git:(master) /Volumes/MyExternal/ExternalRefCode/flutter/bin/flutter --local-engine-src-path=/Volumes/MyExternal/ExternalRefCode/engine/src --local-engine=host_debug_unopt test 
00:03 +0: BuildPreemptPointWidget when build, should call maybePreemptRender                                                                                                     
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
No matching calls (actually, no calls at all).
(If you called `verify(...).called(0);`, please instead use `verifyNever(...);`.)

When the exception was thrown, this was the stack:
#0      fail (package:test_api/src/expect/expect.dart:134:31)
#1      _VerifyCall._checkWith (package:mockito/src/mock.dart:714:7)
#2      _makeVerify.<anonymous closure> (package:mockito/src/mock.dart:991:18)
#3      main.<anonymous closure>.<anonymous closure> (file:///Users/tom/RefCode/flutter_smooth/packages/smooth/test/src/preempt_point_test.dart:18:13)
#4      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:29)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  when build, should call maybePreemptRender
════════════════════════════════════════════════════════════════════════════════════════════════════
00:03 +0 -1: BuildPreemptPointWidget when build, should call maybePreemptRender [E]                                                                                              
  Test failed. See exception logs above.
  The test description was: when build, should call maybePreemptRender
  

To run this test again: /Volumes/MyExternal/ExternalRefCode/flutter/bin/cache/dart-sdk/bin/dart test /Users/tom/RefCode/flutter_smooth/packages/smooth/test/src/preempt_point_test.dart -p vm --plain-name 'BuildPreemptPointWidget when build, should call maybePreemptRender'
00:03 +0 -1: LayoutPreemptPointWidget when layout, should call maybePreemptRender                                                                                                
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
No matching calls (actually, no calls at all).
(If you called `verify(...).called(0);`, please instead use `verifyNever(...);`.)

When the exception was thrown, this was the stack:
#0      fail (package:test_api/src/expect/expect.dart:134:31)
#1      _VerifyCall._checkWith (package:mockito/src/mock.dart:714:7)
#2      _makeVerify.<anonymous closure> (package:mockito/src/mock.dart:991:18)
#3      main.<anonymous closure>.<anonymous closure> (file:///Users/tom/RefCode/flutter_smooth/packages/smooth/test/src/preempt_point_test.dart:26:13)
#4      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:29)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  when layout, should call maybePreemptRender
════════════════════════════════════════════════════════════════════════════════════════════════════
00:03 +0 -2: LayoutPreemptPointWidget when layout, should call maybePreemptRender [E]                                                                                            
  Test failed. See exception logs above.
  The test description was: when layout, should call maybePreemptRender
  

To run this test again: /Volumes/MyExternal/ExternalRefCode/flutter/bin/cache/dart-sdk/bin/dart test /Users/tom/RefCode/flutter_smooth/packages/smooth/test/src/preempt_point_test.dart -p vm --plain-name 'LayoutPreemptPointWidget when layout, should call maybePreemptRender'
00:03 +0 -2: Some tests failed.
