### ISSUE TITLE
Reproduce `list_text_layout.dart` and demonstrate how flutter_smooth solves it

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_smooth#173]
@dnfield in https://discord.com/channels/608014603317936148/1039667632342835250/1039710167329165342

---

Remark: I will mark a lot of my comments below as resolved, since they are solely used as external memory of my brain instead of real discussions with people interested in this thread. (Originally thought only me in this thread so do so)

**Comment by fzyzcjy** [comment]
done: briefly impl it

**Comment by fzyzcjy** [comment]
next: update local env to make it compile

**Comment by fzyzcjy** [comment]
wait, need to update to latest

**Comment by fzyzcjy** [comment]
* https://github.com/fzyzcjy/flutter_smooth/issues/177

**Comment by fzyzcjy** [comment]
```
(base) ➜  flutter git:(flutter-smooth) ninja -C /Volumes/MyExternal/ExternalRefCode/engine/src/out/host_debug_unopt

(base) ➜  flutter git:(flutter-smooth) ninja -C /Volumes/MyExternal/ExternalRefCode/engine/src/out/android_debug_unopt_x64

**Comment by fzyzcjy** [comment]
```
(base) ➜  flutter git:(flutter-smooth) ninja -C /Volumes/MyExternal/ExternalRefCode/engine/src/out/android_debug_unopt_x64; /Volumes/MyExternal/ExternalRefCode/flutter/bin/flutter --local-engine-src-path=/Volumes/MyExternal/ExternalRefCode/engine/src --local-engine=android_debug_unopt_x64 run --device-id emulator-5554

**Comment by fzyzcjy** [comment]
seems not refresh

**Comment by fzyzcjy** [comment]
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _CastError was thrown building Builder(dirty, dependencies: [Directionality]):
Null check operator used on a null value

The relevant error-causing widget was:
  ListTile
  ListTile:file:///Users/tom/RefCode/flutter_smooth/packages/smooth/example/lib/example_list_text_layout/sub_page.dart
  :71:28

When the exception was thrown, this was the stack:
#0      _InkState._build (package:flutter/src/material/ink_decoration.dart:288:45)
#1      Builder.build (package:flutter/src/widgets/basic.dart:7448:48)
#2      StatelessElement.build (package:flutter/src/widgets/framework.dart:5038:49)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4968:15)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
...     Normal element mounting (95 frames)
#101    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#102    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#103    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
#104    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#105    Element.updateChild (package:flutter/src/widgets/framework.dart:3676:20)
#106    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#107    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#109    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#110    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#111    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#113    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#114    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#115    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#116    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#117    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#118    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#120    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#121    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#123    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#124    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#126    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#127    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#128    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#129    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#131    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#132    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#133    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#134    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#136    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#137    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#138    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#139    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#140    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#141    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#142    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#143    AuxiliaryTreePack.runPipeline.<anonymous closure>.<anonymous closure>
(package:smooth/src/infra/auxiliary_tree_pack.dart:107:21)
#144    Timeline.timeSync (dart:developer/timeline.dart:166:22)
#145    AuxiliaryTreePack.runPipeline.<anonymous closure> (package:smooth/src/infra/auxiliary_tree_pack.dart:97:16)
#146    AuxiliaryTreePack._withDebugRunPipelineReason (package:smooth/src/infra/auxiliary_tree_pack.dart:144:11)
#147    AuxiliaryTreePack.runPipeline (package:smooth/src/infra/auxiliary_tree_pack.dart:96:5)
#148    _SmoothPipelineOwner._handleAfterFlushLayout (package:smooth/src/infra/binding.dart:283:12)
#149    _SmoothPipelineOwner.flushLayout (package:smooth/src/infra/binding.dart:252:5)
#150    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:516:19)
#151    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:869:13)
#152    SmoothWidgetsBindingMixin.drawFrame (package:smooth/src/infra/binding.dart:183:11)
#153    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#154    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1309:15)
#155    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1237:9)
#156    SmoothSchedulerBindingMixin.handleDrawFrame (package:smooth/src/infra/binding.dart:75:11)
#157    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1092:5)
#158    _invoke (dart:ui/hooks.dart:145:13)
#159    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#160    _drawFrame (dart:ui/hooks.dart:112:31)

**Comment by fzyzcjy** [comment]
![image](https://user-images.githubusercontent.com/5236035/203459501-a9495e0e-a008-4aef-846b-5827616e9a4c.png)

**Comment by fzyzcjy** [comment]
wrong usage - should not put those children into smooth, contrary to def

**Comment by fzyzcjy** [comment]
repro:

```
class TestPage extends StatefulWidget {
  const TestPage({super.key});

  @override
  State<TestPage> createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  @override
  Widget build(BuildContext context) {
    return SmoothBuilder(
      builder: (context, child) => child,
      child: const CircularProgressIndicator(),
    );
  }
}

**Comment by fzyzcjy** [comment]
<details>

```
class TestPage extends StatefulWidget {
  const TestPage({super.key});

  @override
  State<TestPage> createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  @override
  Widget build(BuildContext context) {
    return SmoothBuilder(
      builder: (context, child) {
        return _Always(child: child);
      },
      child: const CircularProgressIndicator(),
    );
  }
}

class _Always extends SingleChildRenderObjectWidget {
  final VoidCallback? onPerformLayout;
  final Object? debugToken;

  const _Always({
    super.key,
    this.onPerformLayout,
    this.debugToken,
    super.child,
  });

  @override
  // ignore: library_private_types_in_public_api
  _RenderAlwaysLayoutBuilder createRenderObject(BuildContext context) =>
      _RenderAlwaysLayoutBuilder(
        onPerformLayout: onPerformLayout,
        debugToken: debugToken,
      );

  @override
  void updateRenderObject(
      BuildContext context,
      // ignore: library_private_types_in_public_api
      _RenderAlwaysLayoutBuilder renderObject) {
    renderObject
      ..onPerformLayout = onPerformLayout
      ..debugToken = debugToken;
  }
}

class _RenderAlwaysLayoutBuilder extends RenderProxyBox {
  _RenderAlwaysLayoutBuilder({
    required this.onPerformLayout,
    required this.debugToken,
    RenderBox? child,
  }) : super(child);

  VoidCallback? onPerformLayout;
  Object? debugToken;

  @override
  void performLayout() {
    print('$runtimeType.performLayout');

    super.performLayout();
    onPerformLayout?.call();
    SchedulerBinding.instance.addPostFrameCallback((_) => markNeedsLayout());
  }

  @override
  void paint(PaintingContext context, Offset offset) {
    print('$runtimeType.paint');
    SchedulerBinding.instance.addPostFrameCallback((_) => markNeedsPaint());
  }
}


Performing hot restart...                                               
Restarted application in 1,669ms.
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 1            (warm-up frame) ▄▄▄▄▄▄▄▄
I/flutter (28783): ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
D/EGL_emulation(28783): app_time_stats: avg=4441.13ms min=11.29ms max=39845.42ms count=9
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 2                        0ms ▄▄▄▄▄▄▄▄
I/flutter (28783): ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 3              39s 917.465ms ▄▄▄▄▄▄▄▄
I/flutter (28783): _RenderAlwaysLayoutBuilder.performLayout
I/flutter (28783): _RenderAdapterInAuxiliaryTree.performLayout called
I/flutter (28783): _RenderAlwaysLayoutBuilder.paint
D/EGL_emulation(28783): app_time_stats: avg=800.45ms min=73.44ms max=1527.46ms count=2
I/flutter (28783): ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 4              41s 500.830ms ▄▄▄▄▄▄▄▄
I/flutter (28783): _RenderAlwaysLayoutBuilder.performLayout
I/flutter (28783): _RenderAlwaysLayoutBuilder.paint
I/flutter (28783): ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 5              41s 584.165ms ▄▄▄▄▄▄▄▄
I/flutter (28783): _RenderAlwaysLayoutBuilder.performLayout
I/flutter (28783): _RenderAlwaysLayoutBuilder.paint
I/flutter (28783): ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 6              41s 616.706ms ▄▄▄▄▄▄▄▄
I/flutter (28783): _RenderAlwaysLayoutBuilder.performLayout
I/flutter (28783): _RenderAlwaysLayoutBuilder.paint
I/flutter (28783): ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 7              41s 633.373ms ▄▄▄▄▄▄▄▄
I/flutter (28783): _RenderAlwaysLayoutBuilder.performLayout
I/flutter (28783): _RenderAlwaysLayoutBuilder.paint
I/flutter (28783): ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 8              41s 650.040ms ▄▄▄▄▄▄▄▄
I/flutter (28783): _RenderAlwaysLayoutBuilder.performLayout
I/flutter (28783): _RenderAlwaysLayoutBuilder.paint
I/flutter (28783): ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 9              41s 666.659ms ▄▄▄▄▄▄▄▄
I/flutter (28783): _RenderAlwaysLayoutBuilder.performLayout
I/flutter (28783): _RenderAlwaysLayoutBuilder.paint
I/flutter (28783): ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 10             41s 683.326ms ▄▄▄▄▄▄▄▄
I/flutter (28783): _RenderAlwaysLayoutBuilder.performLayout
I/flutter (28783): _RenderAlwaysLayoutBuilder.paint
I/flutter (28783): ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 11             41s 699.993ms ▄▄▄▄▄▄▄▄
I/flutter (28783): _RenderAlwaysLayoutBuilder.performLayout
I/flutter (28783): _RenderAlwaysLayoutBuilder.paint
I/flutter (28783): ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 12             41s 716.749ms ▄▄▄▄▄▄▄▄
I/flutter (28783): _RenderAlwaysLayoutBuilder.performLayout
I/flutter (28783): _RenderAlwaysLayoutBuilder.paint
I/flutter (28783): ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 13             41s 750.083ms ▄▄▄▄▄▄▄▄
I/flutter (28783): _RenderAlwaysLayoutBuilder.performLayout
I/flutter (28783): _RenderAlwaysLayoutBuilder.paint
I/flutter (28783): ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 14             41s 783.329ms ▄▄▄▄▄▄▄▄
I/flutter (28783): _RenderAlwaysLayoutBuilder.performLayout
I/flutter (28783): _RenderAlwaysLayoutBuilder.paint
I/flutter (28783): ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 15             41s 799.996ms ▄▄▄▄▄▄▄▄
I/flutter (28783): _RenderAlwaysLayoutBuilder.performLayout
I/flutter (28783): _RenderAlwaysLayoutBuilder.paint
I/flutter (28783): ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 16             41s 833.330ms ▄▄▄▄▄▄▄▄
I/flutter (28783): _RenderAlwaysLayoutBuilder.performLayout
I/flutter (28783): _RenderAlwaysLayoutBuilder.paint
I/flutter (28783): ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 17             41s 849.997ms ▄▄▄▄▄▄▄▄
I/flutter (28783): _RenderAlwaysLayoutBuilder.performLayout
I/flutter (28783): _RenderAlwaysLayoutBuilder.paint
I/flutter (28783): ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 18             41s 866.664ms ▄▄▄▄▄▄▄▄
I/flutter (28783): _RenderAlwaysLayoutBuilder.performLayout
I/flutter (28783): _RenderAlwaysLayoutBuilder.paint
I/flutter (28783): ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 19             41s 883.331ms ▄▄▄▄▄▄▄▄
I/flutter (28783): _RenderAlwaysLayoutBuilder.performLayout
I/flutter (28783): _RenderAlwaysLayoutBuilder.paint
I/flutter (28783): ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 20             41s 899.998ms ▄▄▄▄▄▄▄▄
I/flutter (28783): _RenderAlwaysLayoutBuilder.performLayout
I/flutter (28783): _RenderAlwaysLayoutBuilder.paint
I/flutter (28783): ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 21             41s 916.810ms ▄▄▄▄▄▄▄▄
I/flutter (28783): _RenderAlwaysLayoutBuilder.performLayout
I/flutter (28783): _RenderAlwaysLayoutBuilder.paint
I/flutter (28783): ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 22             41s 933.477ms ▄▄▄▄▄▄▄▄
I/flutter (28783): _RenderAlwaysLayoutBuilder.performLayout
I/flutter (28783): _RenderAlwaysLayoutBuilder.paint
I/flutter (28783): ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 23             41s 949.991ms ▄▄▄▄▄▄▄▄
I/flutter (28783): _RenderAlwaysLayoutBuilder.performLayout
I/flutter (28783): _RenderAlwaysLayoutBuilder.paint
I/flutter (28783): ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 24             41s 983.326ms ▄▄▄▄▄▄▄▄
I/flutter (28783): _RenderAlwaysLayoutBuilder.performLayout
I/flutter (28783): _RenderAlwaysLayoutBuilder.paint
I/flutter (28783): ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 25              42s 49.994ms ▄▄▄▄▄▄▄▄
I/flutter (28783): _RenderAlwaysLayoutBuilder.performLayout
I/flutter (28783): _RenderAlwaysLayoutBuilder.paint
I/flutter (28783): ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 26              42s 83.351ms ▄▄▄▄▄▄▄▄
I/flutter (28783): _RenderAlwaysLayoutBuilder.performLayout
I/flutter (28783): _RenderAlwaysLayoutBuilder.paint
I/flutter (28783): ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 27             42s 100.018ms ▄▄▄▄▄▄▄▄
I/flutter (28783): _RenderAlwaysLayoutBuilder.performLayout
I/flutter (28783): _RenderAlwaysLayoutBuilder.paint
I/flutter (28783): ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
I/flutter (28783): ▄▄▄▄▄▄▄▄ Frame 28             42s 116.685ms ▄▄▄▄▄▄▄▄
I/flutter (28783): _RenderAlwaysLayoutBuilder.performLayout
I/flutter (28783): _RenderAlwaysLayoutBuilder.paint

```

</details>

**Comment by fzyzcjy** [comment]
paint is never called

recall there were bugs about this long ago?

**Comment by fzyzcjy** [comment]
bug cause:

![image](https://user-images.githubusercontent.com/5236035/203462207-001a0ff8-a568-48fd-9ad9-9160e94a0689.png)

**Comment by fzyzcjy** [comment]
![image](https://user-images.githubusercontent.com/5236035/203462319-f576a673-bc07-4df6-8ab4-dcfc2f8c7677.png)

now 

```
I/flutter (28783): _RenderAdapterInAuxiliaryTree.performLayout called
I/flutter (28783): _RenderAdapterInAuxiliaryTree paint
```

always called

but, content unchanged

**Comment by fzyzcjy** [comment]
next: does _RenderAdapterInMainTree paint to mainSubTreeLayerHandle in every frame?

**Comment by fzyzcjy** [comment]
no!

**Comment by fzyzcjy** [comment]
hack further

![image](https://user-images.githubusercontent.com/5236035/203462461-30ba077f-17aa-4d7f-b9a8-1df41573a833.png)

**Comment by fzyzcjy** [comment]
animation works

**Comment by fzyzcjy** [comment]
now only has this reduced hack, and it still wokrs

![image](https://user-images.githubusercontent.com/5236035/203462692-429a1da6-31d2-4b9a-bab3-1dac3baee486.png)

**Comment by fzyzcjy** [comment]
why is this hack needed? why cannot remove?

**Comment by fzyzcjy** [comment]
theoretically, CircularProgressIndicator should already makes parent paint

**Comment by fzyzcjy** [comment]
```
(base) ➜  ~ ninja -C /Volumes/MyExternal/ExternalRefCode/engine/src/out/android_profile_unopt; /Volumes/MyExternal/ExternalRefCode/flutter/bin/flutter --local-engine-src-path=/Volumes/MyExternal/ExternalRefCode/engine/src --local-engine=android_profile_unopt run --profile --endless-trace-buffer

**Comment by fzyzcjy** [comment]
Unexpected Kernel Format Version 88 (expected 86) when reading file:///Volumes/MyExternal/ExternalRefCode/engine/src/out/android_profile_unopt/flutter_patched_sdk/platform_strong.dill.

**Comment by dnfield** [comment]
Paint doesn't get called for repaint boundaries that are only getting moved without repaint.

**Comment by fzyzcjy** [comment]
@dnfield Hi thanks for the reply! Indeed these text are mostly used for myself to help me thinking (just like external memory). So feel free to ignore them if it is disturbing, and I will ping you later when this demo is done :)

**Comment by fzyzcjy** [comment]
next

```
(base) ➜  flutter git:(flutter-smooth) ninja -C /Volumes/MyExternal/ExternalRefCode/engine/src/out/host_profile_unopt

as well as refreshing
host_debug_unopt
android_profile_unopt

**Comment by fzyzcjy** [comment]
```
(base) ➜  flutter git:(flutter-smooth) ninja -C /Volumes/MyExternal/ExternalRefCode/engine/src/out/android_profile_unopt; /Volumes/MyExternal/ExternalRefCode/flutter/bin/flutter --local-engine-src-path=/Volumes/MyExternal/ExternalRefCode/engine/src --local-engine=android_profile_unopt run --profile --endless-trace-buffer --device-id TRT

**Comment by fzyzcjy** [comment]
initial result

[dart_devtools_2022-11-23_13_16_30.974.json.zip](https://github.com/fzyzcjy/flutter_smooth/files/10072947/dart_devtools_2022-11-23_13_16_30.974.json.zip)

**Comment by fzyzcjy** [comment]
I will close this issue as it has been reproduced. Feel free to create new issues or reply here!
