### ISSUE TITLE
Intercept the `window.render` for both normal pipeline and smooth frames, by implementing own override bindings

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_smooth#22]
- [ ] and add a simple test checking that override

**Comment by fzyzcjy** [comment]
![image](https://user-images.githubusercontent.com/5236035/192661002-7e1c156d-f339-4769-a803-e35395fc4db9.png)

```
(base) ➜  smooth git:(master) ✗ /Volumes/MyExternal/ExternalRefCode/flutter/bin/flutter --local-engine-src-path=/Volumes/MyExternal/ExternalRefCode/engine/src --local-engine=host_debug_unopt test test/src/test_tools/binding.dart
00:01 +0: SmoothSchedulerBindingMixin.onWindowRender                                                                                                                             
hi size=Size(800.0, 600.0)
hi onWindowRender
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following StateError was thrown running a test:
Bad state: A Dart object attempted to access a native peer, but the native peer has been collected
(nullptr). This is usually the result of calling methods on a native-backed object when the native
resources have already been disposed.

When the exception was thrown, this was the stack:
#0      StateError._throwNew (dart:core-patch/errors_patch.dart:168:5)
#1      Scene._toImage (dart:ui/compositing.dart)
#2      Scene.toImage.<anonymous closure> (dart:ui/compositing.dart:51:54)
#3      _futurize (dart:ui/painting.dart:6301:35)
#4      Scene.toImage (dart:ui/compositing.dart:51:12)
#5      main.<anonymous closure> (file:///Users/tom/RefCode/flutter_smooth/packages/smooth/test/src/test_tools/binding.dart:21:39)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  SmoothSchedulerBindingMixin.onWindowRender
════════════════════════════════════════════════════════════════════════════════════════════════════
00:01 +0 -1: SmoothSchedulerBindingMixin.onWindowRender [E]                                                                                                                      
  Test failed. See exception logs above.
  The test description was: SmoothSchedulerBindingMixin.onWindowRender
  

To run this test again: /Volumes/MyExternal/ExternalRefCode/flutter/bin/cache/dart-sdk/bin/dart test /Users/tom/RefCode/flutter_smooth/packages/smooth/test/src/test_tools/binding.dart -p vm --plain-name 'SmoothSchedulerBindingMixin.onWindowRender'
00:02 +0 -1: Some tests failed.

**Comment by fzyzcjy** [comment]
it can get image
![image](https://user-images.githubusercontent.com/5236035/192661428-53694428-5c47-4d24-b3e0-19b4c74d81e5.png)

**Comment by fzyzcjy** [comment]
now refactor
