### ISSUE TITLE
`AutomatedTestWidgetsFlutterBinding.pump` does not provide real timestamp to `handleBeginFrame`, but clamp at milliseconds

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_smooth#48]
- [ ] https://github.com/flutter/flutter/pull/112609
- [ ] https://github.com/flutter/packages/pull/2657

**Comment by fzyzcjy** [comment]
blame

https://github.com/flutter/flutter/blame/master/packages/flutter_test/lib/src/binding.dart

![image](https://user-images.githubusercontent.com/5236035/192924175-263698f7-1d79-439b-93b7-60bbb83b98d1.png)

https://github.com/flutter/flutter/blame/86a490ffe878eeb97393ef762a5cd1ee7df1a61d/packages/flutter_test/lib/src/binding.dart

![image](https://user-images.githubusercontent.com/5236035/192924271-1451867c-1baf-471e-a323-81e09377725f.png)

**Comment by fzyzcjy** [comment]
conclusion: seems that it is there, in the first verison, 7yr ago

**Comment by fzyzcjy** [comment]
make a draft pr to see whether tests pass

**Comment by fzyzcjy** [comment]
## Possibility: that code seems to convert DateTime to Duration, but forget that they are both microseconds

**Comment by fzyzcjy** [comment]
p.s. test fails with old code

![image](https://user-images.githubusercontent.com/5236035/192926239-e83874e6-6dc0-4265-a4d5-dda0c9018bf8.png)
![image](https://user-images.githubusercontent.com/5236035/192926266-e202747f-9e1a-49a2-abf2-a9624bd2c03d.png)

**Comment by fzyzcjy** [comment]
* https://github.com/flutter/flutter/pull/112609

**Comment by fzyzcjy** [comment]
now wait for PR

**Comment by fzyzcjy** [comment]
```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: [0, 17000, 34000, 50000]
  Actual: [0, 16683, 33366, 50049]
   Which: at location [1] is <16683> instead of <17000>
When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///tmp/flutter%20sdk/packages/flutter_test/test/widget_tester_test.dart:173:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
This was caught by the test expectation on the following line:
  file:///tmp/flutter%20sdk/packages/flutter_test/test/widget_tester_test.dart line 173
The test description was:
  pumpFrames
════════════════════════════════════════════════════════════════════════════════════════════════════
00:47 +266 ~2: /tmp/flutter sdk/packages/flutter_test/test/widget_tester_test.dart: pumping pumpFrames                                                                                                 
00:47 +266 ~2 -1: /tmp/flutter sdk/packages/flutter_test/test/widget_tester_test.dart: pumping pumpFrames [E]                                                                                          
  Test failed. See exception logs above.
  The test description was: pumpFrames

**Comment by fzyzcjy** [comment]
```
00:46 +233: /tmp/flutter sdk/packages/flutter_test/test/matchers_test.dart: matchesGoldenFile does not match if comparator throws                                                                      
00:46 +234: /tmp/flutter sdk/packages/flutter_test/test/matchers_test.dart: matchesGoldenFile does not match if comparator throws                                                                      
00:46 +234: /tmp/flutter sdk/packages/flutter_test/test/widget_tester_test.dart: expectLater respects the skip flag                                                                                    
  Skip expect: testing skip
00:46 +234 ~1: /tmp/flutter sdk/packages/flutter_test/test/matchers_test.dart: matchesGoldenFile does not match if comparator throws                                                                   
00:46 +235 ~1: /tmp/flutter sdk/packages/flutter_test/test/matchers_test.dart: matchesGoldenFile does not match if comparator throws                                                                   
00:46 +236 ~1: /tmp/flutter sdk/packages/flutter_test/test/widget_tester_test.dart: Pending timer Throws assertion message without code                                                                
00:46 +236 ~1: /tmp/flutter sdk/packages/flutter_test/test/widget_tester_test.dart: Pending timer Throws assertion message without code                                                                
Pending timers:
Timer (duration: 0:00:01.000000, periodic: false), created:
#0      new FakeTimer._ (package:fake_async/fake_async.dart:308:62)
#1      FakeAsync._createTimer (package:fake_async/fake_async.dart:252:27)
#2      FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:185:19)
#5      main.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///tmp/flutter%20sdk/packages/flutter_test/test/widget_tester_test.dart:814:29)
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:858:19)
<asynchronous suspension>
(elided 2 frames from dart:async)

**Comment by fzyzcjy** [comment]
```
| ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
| The following TestFailure was thrown running a test:
| Expected: 1.0 (±1e-10)
|   Actual: <0.9999833333333332>
|    Which: 0.9999833333333332 is not in the range of 1.0 (±1e-10).
|
| When the exception was thrown, this was the stack:
| #4      main.<anonymous closure> (file:///tmp/flutter_customer_testing.flutter_packages.KWSXGC/tests/packages/animations/test/open_container_test.dart:273:7)
| <asynchronous suspension>
| <asynchronous suspension>
| (elided one frame from package:stack_trace)
|
| This was caught by the test expectation on the following line:
|   file:///tmp/flutter_customer_testing.flutter_packages.KWSXGC/tests/packages/animations/test/open_container_test.dart line 273
| The test description was:
|   Container closes - Fade (by default)
| ════════════════════════════════════════════════════════════════════════════════════════════════════
|
| 00:39 +47 -1: /tmp/flutter_customer_testing.flutter_packages.KWSXGC/tests/packages/animations/test/open_container_test.dart: Container closes - Fade (by default) [E]

**Comment by fzyzcjy** [comment]
![image](https://user-images.githubusercontent.com/5236035/192932575-a6384176-d2af-464b-9704-7ac09f241420.png)

**Comment by fzyzcjy** [comment]
https://github.com/flutter/packages/blob/main/packages/animations/test/open_container_test.dart

**Comment by fzyzcjy** [comment]
pr merged
