### ISSUE TITLE
Add test where content is infinitely slow such that smooth create many extra frames

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_smooth#50]

**Comment by fzyzcjy** [comment]
<details>

![image](https://user-images.githubusercontent.com/5236035/192971104-9f9a177c-5e7a-4d10-b17b-6206195d6ec0.png)
![image](https://user-images.githubusercontent.com/5236035/192971116-c23d28ee-afce-46d7-806d-b0745fab42b8.png)

```
/Volumes/MyExternal/ExternalRefCode/flutter/bin/flutter --no-color test --machine --start-paused --plain-name "multiple preempt points" --local-engine-src-path=/Volumes/MyExternal/ExternalRefCode/engine/src --local-engine=host_debug_unopt test/src/builder_test.dart
Testing started at 15:43 ...

handleAfterFlushLayout
pumpWidget
▄▄▄▄▄▄▄▄ Frame 2                        0ms ▄▄▄▄▄▄▄▄
SimpleAnimatedBuilder.builder animationValue=0.0
AuxiliaryTreePack runPipeline start timeStamp=0:00:00.000000 debugReason=RenderAdapterInMainTree.performLayout
SimpleAnimatedBuilder.builder animationValue=0.0
_RenderAlwaysLayoutBuilder.performLayout
RenderLayoutPreemptPoint.performLayout
Actor.maybePreemptRender shouldAct=false
_RenderAlwaysLayoutBuilder.performLayout
_RenderAlwaysLayoutBuilder.performLayout
RenderLayoutPreemptPoint.performLayout
Actor.maybePreemptRender shouldAct=false
_RenderAlwaysLayoutBuilder.performLayout
_RenderAlwaysLayoutBuilder.performLayout
RenderLayoutPreemptPoint.performLayout
Actor.maybePreemptRender shouldAct=false
_RenderAlwaysLayoutBuilder.performLayout
_RenderAlwaysLayoutBuilder.performLayout
RenderLayoutPreemptPoint.performLayout
Actor.maybePreemptRender shouldAct=false
_RenderAlwaysLayoutBuilder.performLayout
_RenderAlwaysLayoutBuilder.performLayout
RenderLayoutPreemptPoint.performLayout
Actor.maybePreemptRender shouldAct=false
_RenderAlwaysLayoutBuilder.performLayout
_RenderAlwaysLayoutBuilder.performLayout
RenderLayoutPreemptPoint.performLayout
Actor.maybePreemptRender shouldAct=false
_RenderAlwaysLayoutBuilder.performLayout
_RenderAlwaysLayoutBuilder.performLayout
RenderLayoutPreemptPoint.performLayout
Actor.maybePreemptRender shouldAct=false
_RenderAlwaysLayoutBuilder.performLayout
_RenderAlwaysLayoutBuilder.performLayout
RenderLayoutPreemptPoint.performLayout
Actor.maybePreemptRender shouldAct=false
_RenderAlwaysLayoutBuilder.performLayout
_RenderAlwaysLayoutBuilder.performLayout
RenderLayoutPreemptPoint.performLayout
Actor.maybePreemptRender shouldAct=false
_RenderAlwaysLayoutBuilder.performLayout
_RenderAlwaysLayoutBuilder.performLayout
RenderLayoutPreemptPoint.performLayout
Actor.maybePreemptRender shouldAct=false
_RenderAlwaysLayoutBuilder.performLayout
handleAfterFlushLayout
AuxiliaryTreePack runPipeline skip since timeStamp=0:00:00.000000 same as previous
RenderAdapterInMainTree.paint detach the auxiliaryTreeRootLayer
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄ Frame 3                   16.666ms ▄▄▄▄▄▄▄▄
_RenderAlwaysLayoutBuilder.performLayout
RenderLayoutPreemptPoint.performLayout
shouldAct=true now=SimpleDateTime(1664437431097578) nowTimeStamp=0:00:00.016000 shouldActTimeStamp=0:00:00.014666 currentSmoothFrameTimeStamp=0:00:00.016666 currentFrameAdjustedVsyncTargetTimeStamp=0:00:00.016666 currentPreemptRenderVsyncTargetTimeStamp=-0:00:00.016666
Actor.maybePreemptRender shouldAct=true
shouldAct=true now=SimpleDateTime(1664437431097578) nowTimeStamp=0:00:00.016000 shouldActTimeStamp=0:00:00.014666 currentSmoothFrameTimeStamp=0:00:00.016666 currentFrameAdjustedVsyncTargetTimeStamp=0:00:00.016666 currentPreemptRenderVsyncTargetTimeStamp=-0:00:00.016666
AuxiliaryTreePack runPipeline start timeStamp=0:00:00.016666 debugReason=preemptModifyLayerTree
SimpleAnimatedBuilder.builder animationValue=0.2
_RenderAlwaysLayoutBuilder.performLayout
_RenderAlwaysLayoutBuilder.performLayout
RenderLayoutPreemptPoint.performLayout
shouldAct=true now=SimpleDateTime(1664437431113578) nowTimeStamp=0:00:00.032000 shouldActTimeStamp=0:00:00.031332 currentSmoothFrameTimeStamp=0:00:00.016666 currentFrameAdjustedVsyncTargetTimeStamp=0:00:00.016666 currentPreemptRenderVsyncTargetTimeStamp=0:00:00.016666
Actor.maybePreemptRender shouldAct=true
shouldAct=true now=SimpleDateTime(1664437431113578) nowTimeStamp=0:00:00.032000 shouldActTimeStamp=0:00:00.031332 currentSmoothFrameTimeStamp=0:00:00.016666 currentFrameAdjustedVsyncTargetTimeStamp=0:00:00.016666 currentPreemptRenderVsyncTargetTimeStamp=0:00:00.016666
AuxiliaryTreePack runPipeline start timeStamp=0:00:00.033332 debugReason=preemptModifyLayerTree
SimpleAnimatedBuilder.builder animationValue=0.4
_RenderAlwaysLayoutBuilder.performLayout
_RenderAlwaysLayoutBuilder.performLayout
RenderLayoutPreemptPoint.performLayout
shouldAct=true now=SimpleDateTime(1664437431129578) nowTimeStamp=0:00:00.048000 shouldActTimeStamp=0:00:00.047998 currentSmoothFrameTimeStamp=0:00:00.033332 currentFrameAdjustedVsyncTargetTimeStamp=0:00:00.016666 currentPreemptRenderVsyncTargetTimeStamp=0:00:00.033332
Actor.maybePreemptRender shouldAct=true
shouldAct=true now=SimpleDateTime(1664437431129578) nowTimeStamp=0:00:00.048000 shouldActTimeStamp=0:00:00.047998 currentSmoothFrameTimeStamp=0:00:00.033332 currentFrameAdjustedVsyncTargetTimeStamp=0:00:00.016666 currentPreemptRenderVsyncTargetTimeStamp=0:00:00.033332
AuxiliaryTreePack runPipeline start timeStamp=0:00:00.049998 debugReason=preemptModifyLayerTree
SimpleAnimatedBuilder.builder animationValue=0.6
_RenderAlwaysLayoutBuilder.performLayout
_RenderAlwaysLayoutBuilder.performLayout
RenderLayoutPreemptPoint.performLayout
Actor.maybePreemptRender shouldAct=false
_RenderAlwaysLayoutBuilder.performLayout
_RenderAlwaysLayoutBuilder.performLayout
RenderLayoutPreemptPoint.performLayout
shouldAct=true now=SimpleDateTime(1664437431161578) nowTimeStamp=0:00:00.080000 shouldActTimeStamp=0:00:00.064664 currentSmoothFrameTimeStamp=0:00:00.049998 currentFrameAdjustedVsyncTargetTimeStamp=0:00:00.016666 currentPreemptRenderVsyncTargetTimeStamp=0:00:00.049998
Actor.maybePreemptRender shouldAct=true
shouldAct=true now=SimpleDateTime(1664437431161578) nowTimeStamp=0:00:00.080000 shouldActTimeStamp=0:00:00.064664 currentSmoothFrameTimeStamp=0:00:00.049998 currentFrameAdjustedVsyncTargetTimeStamp=0:00:00.016666 currentPreemptRenderVsyncTargetTimeStamp=0:00:00.049998
AuxiliaryTreePack runPipeline start timeStamp=0:00:00.083330 debugReason=preemptModifyLayerTree
SimpleAnimatedBuilder.builder animationValue=1.0
_RenderAlwaysLayoutBuilder.performLayout
_RenderAlwaysLayoutBuilder.performLayout
RenderLayoutPreemptPoint.performLayout
Actor.maybePreemptRender shouldAct=false
_RenderAlwaysLayoutBuilder.performLayout
_RenderAlwaysLayoutBuilder.performLayout
RenderLayoutPreemptPoint.performLayout
shouldAct=true now=SimpleDateTime(1664437431193578) nowTimeStamp=0:00:00.112000 shouldActTimeStamp=0:00:00.097996 currentSmoothFrameTimeStamp=0:00:00.083330 currentFrameAdjustedVsyncTargetTimeStamp=0:00:00.016666 currentPreemptRenderVsyncTargetTimeStamp=0:00:00.083330
Actor.maybePreemptRender shouldAct=true
shouldAct=true now=SimpleDateTime(1664437431193578) nowTimeStamp=0:00:00.112000 shouldActTimeStamp=0:00:00.097996 currentSmoothFrameTimeStamp=0:00:00.083330 currentFrameAdjustedVsyncTargetTimeStamp=0:00:00.016666 currentPreemptRenderVsyncTargetTimeStamp=0:00:00.083330
AuxiliaryTreePack runPipeline start timeStamp=0:00:00.116662 debugReason=preemptModifyLayerTree
SimpleAnimatedBuilder.builder animationValue=1.0
_RenderAlwaysLayoutBuilder.performLayout
_RenderAlwaysLayoutBuilder.performLayout
RenderLayoutPreemptPoint.performLayout
Actor.maybePreemptRender shouldAct=false
_RenderAlwaysLayoutBuilder.performLayout
_RenderAlwaysLayoutBuilder.performLayout
RenderLayoutPreemptPoint.performLayout
shouldAct=true now=SimpleDateTime(1664437431225578) nowTimeStamp=0:00:00.144000 shouldActTimeStamp=0:00:00.131328 currentSmoothFrameTimeStamp=0:00:00.116662 currentFrameAdjustedVsyncTargetTimeStamp=0:00:00.016666 currentPreemptRenderVsyncTargetTimeStamp=0:00:00.116662
Actor.maybePreemptRender shouldAct=true
shouldAct=true now=SimpleDateTime(1664437431225578) nowTimeStamp=0:00:00.144000 shouldActTimeStamp=0:00:00.131328 currentSmoothFrameTimeStamp=0:00:00.116662 currentFrameAdjustedVsyncTargetTimeStamp=0:00:00.016666 currentPreemptRenderVsyncTargetTimeStamp=0:00:00.116662
AuxiliaryTreePack runPipeline start timeStamp=0:00:00.149994 debugReason=preemptModifyLayerTree
_RenderAlwaysLayoutBuilder.performLayout
_RenderAlwaysLayoutBuilder.performLayout
RenderLayoutPreemptPoint.performLayout
Actor.maybePreemptRender shouldAct=false
_RenderAlwaysLayoutBuilder.performLayout
handleAfterFlushLayout
AuxiliaryTreePack runPipeline start timeStamp=0:00:00.166660 debugReason=SmoothPipelineOwner.handleAfterFlushLayout
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
WindowRenderCapturer.expect save failed images to disk
Save image to failure_0_actual.png
Save image to failure_1_actual.png
Save image to failure_2_actual.png
Save image to failure_3_actual.png
Save image to failure_4_actual.png
Save image to failure_5_actual.png
Save image to failure_6_actual.png
Save image to failure_0_expect.png
Save image to failure_1_expect.png
Save image to failure_2_expect.png
Save image to failure_3_expect.png
Save image to failure_4_expect.png
Save image to failure_5_expect.png
Save image to failure_6_expect.png
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: rasterized image matches that of a [100×50] reference image
  Actual: Image:<[100×50]>
   Which: does not match on 2500 pixels
context: i=3

When the exception was thrown, this was the stack:
#0      fail (package:test_api/src/expect/expect.dart:134:31)
#1      _expect.<anonymous closure> (package:test_api/src/expect/expect.dart:109:9)
<asynchronous suspension>
<asynchronous suspension>
(elided 6 frames from dart:async and package:stack_trace)

The test description was:
  multiple preempt points
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: multiple preempt points


```

</details>
