### ISSUE TITLE
Get called when main tree `flushLayout` is finished

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_smooth#52]
why: https://github.com/fzyzcjy/flutter_smooth/issues/23#issuecomment-1261691891

**Comment by fzyzcjy** [comment]
looks like it is called.

<details>

```
/Volumes/MyExternal/ExternalRefCode/flutter/bin/flutter --no-color test --machine --start-paused --plain-name "when one extra smooth frame" --local-engine-src-path=/Volumes/MyExternal/ExternalRefCode/engine/src --local-engine=host_debug_unopt test/src/builder_test.dart
Testing started at 11:50 ...

TODO _handleAfterFlushLayout now=2022-09-29 11:51:00.034637
pumpWidget
▄▄▄▄▄▄▄▄ Frame 2                        0ms ▄▄▄▄▄▄▄▄
SimpleAnimatedBuilder.builder animationValue=0.0
first slow builder elapseBlocking for 0:00:00.000000 (p.s. currentFrameTimeStamp=0:00:00.000000)
AuxiliaryTreePack runPipeline start timeStamp=0:00:00.000000 debugReason=RenderAdapterInMainTree.performLayout
SimpleAnimatedBuilder.builder animationValue=0.0
RenderLayoutPreemptPoint.performLayout
Actor.maybePreemptRender shouldAct=false
_RenderAlwaysLayoutBuilder.performLayout
_RenderAlwaysLayoutBuilder.performLayout
second slow layout elapseBlocking for 0:00:00.000000 (p.s. currentFrameTimeStamp=0:00:00.000000)
TODO _handleAfterFlushLayout now=2022-09-29 11:51:00.034637
RenderAdapterInMainTree.paint detach the auxiliaryTreeRootLayer
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
action: pump now=2022-09-29 11:51:00.034637
▄▄▄▄▄▄▄▄ Frame 3                   16.666ms ▄▄▄▄▄▄▄▄
first slow builder elapseBlocking for 0:00:00.015500 (p.s. currentFrameTimeStamp=0:00:00.016666)
RenderLayoutPreemptPoint.performLayout
shouldAct=true now=SimpleDateTime(1664423460066803) nowTimeStamp=0:00:00.015500 shouldActTimeStamp=0:00:00.014666 currentSmoothFrameTimeStamp=0:00:00.016666 currentFrameAdjustedVsyncTargetTimeStamp=0:00:00.016666 currentPreemptRenderVsyncTargetTimeStamp=-2:46:40.000000
Actor.maybePreemptRender shouldAct=true
AuxiliaryTreePack runPipeline start timeStamp=0:00:00.016666 debugReason=preemptModifyLayerTree
SimpleAnimatedBuilder.builder animationValue=0.1
shouldAct=true now=SimpleDateTime(1664423460066803) nowTimeStamp=0:00:00.015500 shouldActTimeStamp=0:00:00.014666 currentSmoothFrameTimeStamp=0:00:00.016666 currentFrameAdjustedVsyncTargetTimeStamp=0:00:00.016666 currentPreemptRenderVsyncTargetTimeStamp=-2:46:40.000000
_RenderAlwaysLayoutBuilder.performLayout
_RenderAlwaysLayoutBuilder.performLayout
second slow layout elapseBlocking for 0:00:00.015500 (p.s. currentFrameTimeStamp=0:00:00.016666)
TODO _handleAfterFlushLayout now=2022-09-29 11:51:00.082303
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
WindowRenderCapturer.expect save failed images to disk
Save image to failure_0_actual.png
Save image to failure_1_actual.png
Save image to failure_0_expect.png
Save image to failure_1_expect.png
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: rasterized image matches that of a [100×50] reference image
  Actual: Image:<[100×50]>
   Which: does not match on 2500 pixels

When the exception was thrown, this was the stack:
#0      fail (package:test_api/src/expect/expect.dart:134:31)
#1      _expect.<anonymous closure> (package:test_api/src/expect/expect.dart:109:9)
<asynchronous suspension>
<asynchronous suspension>
(elided 6 frames from dart:async and package:stack_trace)

The test description was:
  when one extra smooth frame
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: when one extra smooth frame


```

</details>
