### ISSUE TITLE
When running 'when one extra smooth frame' test alone, it works; but when run with others in same file, it fails

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_smooth#56]

**Comment by fzyzcjy** [comment]
![image](https://user-images.githubusercontent.com/5236035/192948428-394d9eaa-94f5-423f-93b8-0a883156e9f4.png)


<details>

```
handleAfterFlushLayout
pumpWidget
▄▄▄▄▄▄▄▄ Frame 8                        0ms ▄▄▄▄▄▄▄▄
SimpleAnimatedBuilder.builder animationValue=0.0
first slow builder elapseBlocking for 0:00:00.000000 (p.s. currentFrameTimeStamp=0:00:00.000000)
AuxiliaryTreePack runPipeline start timeStamp=0:00:00.000000 debugReason=RenderAdapterInMainTree.performLayout
SimpleAnimatedBuilder.builder animationValue=0.0
RenderLayoutPreemptPoint.performLayout
Actor.maybePreemptRender shouldAct=false
_RenderAlwaysLayoutBuilder.performLayout
_RenderAlwaysLayoutBuilder.performLayout
second slow layout elapseBlocking for 0:00:00.000000 (p.s. currentFrameTimeStamp=0:00:00.000000)
handleAfterFlushLayout
AuxiliaryTreePack runPipeline skip since timeStamp=0:00:00.000000 same as previous
RenderAdapterInMainTree.paint detach the auxiliaryTreeRootLayer
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
action: pump now=2022-09-29 13:41:07.824922
▄▄▄▄▄▄▄▄ Frame 9                   16.666ms ▄▄▄▄▄▄▄▄
first slow builder elapseBlocking for 0:00:00.015500 (p.s. currentFrameTimeStamp=0:00:00.016666)
RenderLayoutPreemptPoint.performLayout
Actor.maybePreemptRender shouldAct=false
_RenderAlwaysLayoutBuilder.performLayout
_RenderAlwaysLayoutBuilder.performLayout
second slow layout elapseBlocking for 0:00:00.015500 (p.s. currentFrameTimeStamp=0:00:00.016666)
handleAfterFlushLayout
AuxiliaryTreePack runPipeline start timeStamp=0:00:00.016666 debugReason=SmoothPipelineOwner.handleAfterFlushLayout
SimpleAnimatedBuilder.builder animationValue=0.1
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
WindowRenderCapturer.expect save failed images to disk
Save image to failure_0_actual.png
Save image to failure_0_expect.png
Save image to failure_1_expect.png
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: <2>
  Actual: <1>

When the exception was thrown, this was the stack:
#4      WindowRenderCapturer.expect (file:///Users/tom/RefCode/flutter_smooth/packages/smooth/test/src/test_tools/binding.dart:112:20)
#5      main.<anonymous closure>.<anonymous closure> (file:///Users/tom/RefCode/flutter_smooth/packages/smooth/test/src/builder_test.dart:136:22)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/tom/RefCode/flutter_smooth/packages/smooth/test/src/test_tools/binding.dart line 112
The test description was:
  when one extra smooth frame
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: when one extra smooth frame


```

</details>

![image](https://user-images.githubusercontent.com/5236035/192948459-e8887105-4d90-405a-b81e-808c063e62f6.png)

<details>

```
/Volumes/MyExternal/ExternalRefCode/flutter/bin/flutter --no-color test --machine --start-paused --plain-name "when one extra smooth frame" --local-engine-src-path=/Volumes/MyExternal/ExternalRefCode/engine/src --local-engine=host_debug_unopt test/src/builder_test.dart
Testing started at 13:42 ...

handleAfterFlushLayout
pumpWidget
▄▄▄▄▄▄▄▄ Frame 2                        0ms ▄▄▄▄▄▄▄▄
SimpleAnimatedBuilder.builder animationValue=0.0
first slow builder elapseBlocking for 0:00:00.000000 (p.s. currentFrameTimeStamp=0:00:00.000000)
AuxiliaryTreePack runPipeline start timeStamp=0:00:00.000000 debugReason=RenderAdapterInMainTree.performLayout
SimpleAnimatedBuilder.builder animationValue=0.0
RenderLayoutPreemptPoint.performLayout
Actor.maybePreemptRender shouldAct=false
_RenderAlwaysLayoutBuilder.performLayout
_RenderAlwaysLayoutBuilder.performLayout
second slow layout elapseBlocking for 0:00:00.000000 (p.s. currentFrameTimeStamp=0:00:00.000000)
handleAfterFlushLayout
AuxiliaryTreePack runPipeline skip since timeStamp=0:00:00.000000 same as previous
RenderAdapterInMainTree.paint detach the auxiliaryTreeRootLayer
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
action: pump now=2022-09-29 13:42:27.015953
▄▄▄▄▄▄▄▄ Frame 3                   16.666ms ▄▄▄▄▄▄▄▄
first slow builder elapseBlocking for 0:00:00.015500 (p.s. currentFrameTimeStamp=0:00:00.016666)
RenderLayoutPreemptPoint.performLayout
shouldAct=true now=SimpleDateTime(1664430147048119) nowTimeStamp=0:00:00.015500 shouldActTimeStamp=0:00:00.014666 currentSmoothFrameTimeStamp=0:00:00.016666 currentFrameAdjustedVsyncTargetTimeStamp=0:00:00.016666 currentPreemptRenderVsyncTargetTimeStamp=-0:00:00.016666
Actor.maybePreemptRender shouldAct=true
shouldAct=true now=SimpleDateTime(1664430147048119) nowTimeStamp=0:00:00.015500 shouldActTimeStamp=0:00:00.014666 currentSmoothFrameTimeStamp=0:00:00.016666 currentFrameAdjustedVsyncTargetTimeStamp=0:00:00.016666 currentPreemptRenderVsyncTargetTimeStamp=-0:00:00.016666
AuxiliaryTreePack runPipeline start timeStamp=0:00:00.016666 debugReason=preemptModifyLayerTree
SimpleAnimatedBuilder.builder animationValue=0.1
_RenderAlwaysLayoutBuilder.performLayout
_RenderAlwaysLayoutBuilder.performLayout
second slow layout elapseBlocking for 0:00:00.015500 (p.s. currentFrameTimeStamp=0:00:00.016666)
handleAfterFlushLayout
AuxiliaryTreePack runPipeline start timeStamp=0:00:00.033332 debugReason=SmoothPipelineOwner.handleAfterFlushLayout
SimpleAnimatedBuilder.builder animationValue=0.2
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄ Frame 4                   47.666ms ▄▄▄▄▄▄▄▄
handleAfterFlushLayout
AuxiliaryTreePack runPipeline start timeStamp=0:00:00.047666 debugReason=SmoothPipelineOwner.handleAfterFlushLayout
SimpleAnimatedBuilder.builder animationValue=0.2860074402976119
AuxiliaryTreePack runPipeline start timeStamp=0:00:00.047666 debugReason=AuxiliaryTreePack.dispose
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
handleAfterFlushLayout

```

</details>

**Comment by fzyzcjy** [comment]
Actor.maybePreemptRender shouldAct=false, while it should be true

**Comment by fzyzcjy** [comment]
## thought: maybe we should reset PreemptStrategyNormal fields, currently seem to preserve value across tests?

**Comment by fzyzcjy** [comment]
## indeed, should reset *everything* across tests, not only those values

**Comment by fzyzcjy** [comment]
## [TODO] what to do?

**Comment by fzyzcjy** [comment]
![image](https://user-images.githubusercontent.com/5236035/192950416-89de62e6-2a38-43f9-82c4-33764b387ed8.png)
