### ISSUE TITLE
Add sanity check for `onBeginFrame` duration input

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_smooth#61]

**Comment by fzyzcjy** [comment]
<details>

```
/Volumes/MyExternal/ExternalRefCode/flutter/bin/flutter --no-color test --machine --start-paused --local-engine-src-path=/Volumes/MyExternal/ExternalRefCode/engine/src --local-engine=host_debug_unopt test/src/builder_test.dart
Testing started at 14:46 ...

handleAfterFlushLayout
handleAfterFlushLayout
handleAfterFlushLayout
handleAfterFlushLayout
AuxiliaryTreePack runPipeline start timeStamp=0:00:00.000000 debugReason=RenderAdapterInMainTree.performLayout
handleAfterFlushLayout
AuxiliaryTreePack runPipeline skip since timeStamp=0:00:00.000000 same as previous
RenderAdapterInMainTree.paint detach the auxiliaryTreeRootLayer
handleAfterFlushLayout
AuxiliaryTreePack runPipeline skip since timeStamp=0:00:00.000000 same as previous
AuxiliaryTreePack runPipeline start timeStamp=0:00:00.000000 debugReason=AuxiliaryTreePack.dispose
handleAfterFlushLayout
pumpWidget
▄▄▄▄▄▄▄▄ Frame 8                        0ms ▄▄▄▄▄▄▄▄
SimpleAnimatedBuilder.builder animationValue=0.0
first slow builder elapseBlocking for 0:00:00.000000 (p.s. currentFrameTimeStamp=0:00:00.000000)
AuxiliaryTreePack runPipeline start timeStamp=0:00:00.000000 debugReason=RenderAdapterInMainTree.performLayout
SimpleAnimatedBuilder.builder animationValue=0.0
RenderLayoutPreemptPoint.performLayout
Actor.maybePreemptRender shouldAct=false
_RenderAlwaysLayoutBuilder.performLayout
_RenderAlwaysLayoutBuilder.performLayout
second slow layout elapseBlocking for 0:00:00.000000 (p.s. currentFrameTimeStamp=0:00:00.000000)
handleAfterFlushLayout
AuxiliaryTreePack runPipeline skip since timeStamp=0:00:00.000000 same as previous
RenderAdapterInMainTree.paint detach the auxiliaryTreeRootLayer
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
action: pump now=2022-09-29 14:46:51.703508
▄▄▄▄▄▄▄▄ Frame 9                   16.666ms ▄▄▄▄▄▄▄▄
first slow builder elapseBlocking for 0:00:00.015500 (p.s. currentFrameTimeStamp=0:00:00.016666)
RenderLayoutPreemptPoint.performLayout
shouldAct=true now=SimpleDateTime(1664434011735674) nowTimeStamp=0:00:00.015500 shouldActTimeStamp=0:00:00.014666 currentSmoothFrameTimeStamp=0:00:00.016666 currentFrameAdjustedVsyncTargetTimeStamp=0:00:00.016666 currentPreemptRenderVsyncTargetTimeStamp=-0:00:00.016666
Actor.maybePreemptRender shouldAct=true
shouldAct=true now=SimpleDateTime(1664434011735674) nowTimeStamp=0:00:00.015500 shouldActTimeStamp=0:00:00.014666 currentSmoothFrameTimeStamp=0:00:00.016666 currentFrameAdjustedVsyncTargetTimeStamp=0:00:00.016666 currentPreemptRenderVsyncTargetTimeStamp=-0:00:00.016666
AuxiliaryTreePack runPipeline start timeStamp=0:00:00.016666 debugReason=preemptModifyLayerTree
SimpleAnimatedBuilder.builder animationValue=0.1
_RenderAlwaysLayoutBuilder.performLayout
_RenderAlwaysLayoutBuilder.performLayout
second slow layout elapseBlocking for 0:00:00.015500 (p.s. currentFrameTimeStamp=0:00:00.016666)
handleAfterFlushLayout
AuxiliaryTreePack runPipeline start timeStamp=0:00:00.033332 debugReason=SmoothPipelineOwner.handleAfterFlushLayout
SimpleAnimatedBuilder.builder animationValue=0.2
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
action: pump (useless, just for clean up)
▄▄▄▄▄▄▄▄ Frame 10                  49.998ms ▄▄▄▄▄▄▄▄
first slow builder elapseBlocking for 0:00:00.015500 (p.s. currentFrameTimeStamp=0:00:00.049998)
RenderLayoutPreemptPoint.performLayout
shouldAct=true now=SimpleDateTime(1664434011769006) nowTimeStamp=0:00:00.048832 shouldActTimeStamp=0:00:00.047998 currentSmoothFrameTimeStamp=0:00:00.049998 currentFrameAdjustedVsyncTargetTimeStamp=0:00:00.049998 currentPreemptRenderVsyncTargetTimeStamp=0:00:00.033332
Actor.maybePreemptRender shouldAct=true
shouldAct=true now=SimpleDateTime(1664434011769006) nowTimeStamp=0:00:00.048832 shouldActTimeStamp=0:00:00.047998 currentSmoothFrameTimeStamp=0:00:00.049998 currentFrameAdjustedVsyncTargetTimeStamp=0:00:00.049998 currentPreemptRenderVsyncTargetTimeStamp=0:00:00.033332
AuxiliaryTreePack runPipeline start timeStamp=0:00:00.049998 debugReason=preemptModifyLayerTree
SimpleAnimatedBuilder.builder animationValue=0.3
_RenderAlwaysLayoutBuilder.performLayout
_RenderAlwaysLayoutBuilder.performLayout
second slow layout elapseBlocking for 0:00:00.015500 (p.s. currentFrameTimeStamp=0:00:00.049998)
handleAfterFlushLayout
AuxiliaryTreePack runPipeline start timeStamp=0:00:00.066664 debugReason=SmoothPipelineOwner.handleAfterFlushLayout
SimpleAnimatedBuilder.builder animationValue=0.4
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
handleAfterFlushLayout
AuxiliaryTreePack runPipeline start timeStamp=0:00:00.049998 debugReason=SmoothPipelineOwner.handleAfterFlushLayout
SimpleAnimatedBuilder.builder animationValue=0.3
AuxiliaryTreePack runPipeline start timeStamp=0:00:00.049998 debugReason=AuxiliaryTreePack.dispose
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: <0>
  Actual: <14334>
frame timestamp should be multiples of kOneFrame, otherwise Smooth logic will be wrong
currentFrameTimeStamp=0:00:00.080998 prevFrameTimeStamp=0:00:00.049998

When the exception was thrown, this was the stack:
#4      SmoothSchedulerBindingTestMixin.handleBeginFrame (file:///Users/tom/RefCode/flutter_smooth/packages/smooth/test/src/test_tools/binding.dart:80:7)
#5      AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1096:9)
#8      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#9      AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1086:27)
#10     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:866:13)
<asynchronous suspension>
(elided 2 frames from dart:async)

This was caught by the test expectation on the following line:
  file:///Users/tom/RefCode/flutter_smooth/packages/smooth/test/src/test_tools/binding.dart line 80
The test description was:
  when one extra smooth frame
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: when one extra smooth frame


```

</details>

**Comment by fzyzcjy** [comment]
![image](https://user-images.githubusercontent.com/5236035/192959529-ec332db4-00b5-4551-9dfa-83a285827947.png)
